apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "custom-jenkins.fullname" . }}-config
  labels:
    {{- include "custom-jenkins.labels" . | nindent 4 }}
data:
  JAVA_OPTS: {{ .Values.jenkins.javaOpts | quote }}
