apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "custom-jenkins.fullname" . }}
  labels:
    {{- include "custom-jenkins.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "custom-jenkins.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "custom-jenkins.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: jenkins
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetHttpPort }}
            - name: agent
              containerPort: {{ .Values.service.agentPort }}
          env:
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "custom-jenkins.fullname" . }}-config
                  key: JAVA_OPTS
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            {{- if .Values.dockerSocket.enabled }}
            - name: docker-sock
              mountPath: /var/run/docker.sock
            {{- end }}
      volumes:
        - name: jenkins-home
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "custom-jenkins.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.dockerSocket.enabled }}
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        {{- end }}
