apiVersion: v1
kind: Service
metadata:
  name: {{ include "custom-jenkins.fullname" . }}
  labels:
    {{- include "custom-jenkins.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "custom-jenkins.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: agent
      port: {{ .Values.service.agentPort }}
      targetPort: agent
